name: ci

on: [deployment_status]

jobs:
  e2e:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: https://color-ball-sort.vercel.app/
